Feature/Product Page
ignasiusadhitia/final-project-dash pull request #5
Opened 2024-12-21 14:29 UTC by dvpms

Preview:
![image](https://github.com/user-attachments/assets/8c989312-cf16-4ded-9805-887f1aaded34)

2024-12-21 15:46 UTC, rikkriuk commented on src/pages/product/Product.jsx
> +                <th className="px-5 py-3 whitespace-nowrap">Action</th>
Tambahkan ukuran font di setiap th sesuai design (text-sm)

2024-12-21 15:46 UTC, rikkriuk commented on src/pages/product/Product.jsx
> +                  <td className="px-5 py-2 border-b border-gray-200">
Tambahkan ukuran font di setiap th sesuai design

2024-12-21 15:47 UTC, rikkriuk commented on src/pages/product/Product.jsx
> +              </button>
Pakai icon next sesuai design

2024-12-21 15:49 UTC, rikkriuk commented on src/pages/product/Product.jsx
> +            </div>
Usahakan agar rows per page ada di samping next dan prev button sesuai design

2024-12-21 15:51 UTC, rikkriuk reviewed
@dvpms Perlu perbaiki untuk lebih menyesuaikan dengan desgin dari segi layout, ukuran dan warna text

2024-12-22 13:30 UTC, ignasiusadhitia requested changes

2024-12-22 13:30 UTC, ignasiusadhitia commented on src/pages/product/Product.jsx
> +              <tr className="text-left mb-20 ">
```suggestion
              <tr className="text-left mb-20 text-sm">
```

2024-12-23 00:41 UTC, desup1421 approved these changes
![image](https://github.com/user-attachments/assets/58eb4c10-9f63-4700-80ef-cecb90f84895)
Good job! Sudah mencapai standar MVP, bisa dirapihkan kembali nantinya.

2024-12-23 00:52 UTC, ignasiusadhitia requested changes
tolong typo-nya dibetulin dulu mas @dvpms `RightChevron`

2024-12-23 00:52 UTC, ignasiusadhitia commented on src/pages/product/Product.jsx
> +import { LeftChevron, RigthChevron, Delete, Details, Edit } from '@icons';
```suggestion
import { LeftChevron, RightChevron, Delete, Details, Edit } from '@icons';
```

2024-12-23 00:52 UTC, ignasiusadhitia commented on src/pages/product/Product.jsx
> +                  <RigthChevron className="w-4 h-4" />
```suggestion
                  <RightChevron className="w-4 h-4" />
```

2024-12-23 00:52 UTC, ignasiusadhitia commented on src/assets/icons/index.js
> +export { default as RigthChevron } from './rigth-chevron.svg?react';
```suggestion
export { default as RightChevron } from './right-chevron.svg?react';
```

2024-12-23 04:10 UTC, ignasiusadhitia approved these changes
well done 🚀 🚀 🚀

2024-12-23 04:10 UTC, merged